const serviceData = [
  {
    serviceText: "Search Engine Optimization",
    img: "src/assets/Photos/seo.png",
    bgColor: "(--gray)",
    buttonBgcolor: "(--accGreen)",
    buttonBgHove: "black",
    buttonTextColor: "black",
    buttonTextHover: "(--accGreen)",
    buttonBorderHover: "black",
    headingBgColor: "(--accGreen)",
  },
  {
    serviceText: "Pay-per-click advertising",
    img: "src/assets/Photos/ppc.png",
    bgColor: "(--accGreen)",
    buttonBgcolor: "black",
    buttonBgHove: "(--gray)",
    buttonTextColor: "#b9ff66",
    buttonTextHover: "black",
    buttonBorderHover: "black",
    headingBgColor: "white",
  },
  {
    serviceText: "Social Media Marketing",
    img: "src/assets/Photos/smm.png",
    bgColor: "black",
    buttonBgcolor: "white",
    buttonBgHove: "(--accGreen)",
    buttonTextColor: "black",
    buttonTextHover: "black",
    buttonBorderHover: "black",
    headingBgColor: "white",
  },
  {
    serviceText: "Email Marketing",
    img: "src/assets/Photos/em.png",
    bgColor: "(--gray)",
    buttonBgcolor: "(--accGreen)",
    buttonBgHove: "black",
    buttonTextColor: "black",
    buttonTextHover: "(--accGreen)",
    buttonBorderHover: "black",
    headingBgColor: "(--accGreen)",
  },
  {
    serviceText: "Content Creation",
    img: "src/assets/Photos/cc.png",
    bgColor: "(--accGreen)",
    buttonBgcolor: "black",
    buttonBgHove: "(--gray)",
    buttonTextColor: "#b9ff66",
    buttonTextHover: "black",
    buttonBorderHover: "black",
    headingBgColor: "white",
  },
  {
    serviceText: "Analytics and Tracking",
    img: "src/assets/Photos/at.png",
    bgColor: "black",
    buttonBgcolor: "white",
    buttonBgHove: "(--accGreen)",
    buttonTextColor: "black",
    buttonTextHover: "black",
    buttonBorderHover: "black",
    headingBgColor: "white",
  },
];

export default serviceData;
